---
- hosts: appServer
  become: true
  tasks:
  - name: Display the date
    command: date
    register: dateOutPut
    ignore_errors: yes
  - name: Display the contents of dateOutPut
    debug:
     msg: "{{dateOutPut}}"
  - name: Display the std output of dateOutPut 
    debug:
     msg: "{{dateOutPut.stdout}}"
  - name: Display the std error of dateOutPut
    debug:
     msg: "{{dateOutPut.stderr}}"
  - name: Install Apache HTTP server
    yum: name=httpd update_cache=yes state=latest
  - name: Start HTTP Server
    service: name=httpd enabled=yes state=started
...

